application: yontage
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: .*
  script: main.py
